// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrUC4rAndm1X7ntQlCqQ6rBa3BR4gD5EU',
    appId: '1:1023288397226:web:03e5aac5b2cca3b469efd3',
    messagingSenderId: '1023288397226',
    projectId: 'tontine-app-eb2ed',
    authDomain: 'tontine-app-eb2ed.firebaseapp.com',
    storageBucket: 'tontine-app-eb2ed.firebasestorage.app',
    measurementId: 'G-RBXD29R4WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9CNlTnnxTNW7inMNghCwZiaaQBnpN9Ew',
    appId: '1:1023288397226:android:2f5b8956106f301569efd3',
    messagingSenderId: '1023288397226',
    projectId: 'tontine-app-eb2ed',
    storageBucket: 'tontine-app-eb2ed.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrUC4rAndm1X7ntQlCqQ6rBa3BR4gD5EU',
    appId: '1:1023288397226:web:43aa0c2dd7a62a1969efd3',
    messagingSenderId: '1023288397226',
    projectId: 'tontine-app-eb2ed',
    authDomain: 'tontine-app-eb2ed.firebaseapp.com',
    storageBucket: 'tontine-app-eb2ed.firebasestorage.app',
    measurementId: 'G-XJB9G1XN1C',
  );
}
